services:
  mariadb:
    init: true
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - docker-network
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_USER_HOSTNAME: ${MYSQL_USER_HOSTNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
    restart: always

  nginx:
    init: true
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
      - docker-network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html
    environment:
      WORDPRESS_DIR: /var/www/html
    restart: always

  wordpress:
    init: true
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    networks:
      - docker-network
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      WORDPRESS_ADMIN_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      DOMAIN_URL: ${DOMAIN_URL}
    restart: always

networks:
  docker-network:
    name: docker-network

volumes:
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: bind
      o: bind,rw
      device: ${WP_VOLUME_DEVICE}
  database-volume:
    name: database-volume
    driver: local
    driver_opts:
      type: bind
      o: bind,rw
      device: ${DB_VOLUME_DEVICE}

