services:
  mariadb:
    init: true
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:tajeong
    container_name: mariadb
    networks:
      - docker-network
    environment:
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
    # volumes:
    # volumes:
    #   - wordpress-database:

  nginx:
    init: true
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:tajeong
    container_name: nginx
    networks:
      - docker-network
    ports:
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    init: true
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:tajeong
    container_name: wordpress
    networks:
      - docker-network
    depends_on:
      - mariadb
    volumes:
      - wordpress-website:/home/tajeong/data
    environment:
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}

networks:
  docker-network:
    name: docker-network

volumes:
  wordpress-website:
    name: wordpress-website
    driver: local
    driver_opts:
      type: bind
      o: bind,rw
      # device: "/home/tajeong/data/wp"
      device: /Users/jeongtaejun/Documents/develop/42project/42cursus/inception/home/tajeong/data/wp
  # wordpress-database:
  #   name: wordpress-website
  #   driver: local
  #   driver_opts:
  #     type: bind
  #     o: bind,rw
  #     # device: "/home/tajeong/data/db"
  #     device: /Users/jeongtaejun/Documents/develop/42project/42cursus/inception/home/tajeong/data/db

